apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
  namespace: default
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: my-app-stable
      previewService: my-app-preview
      autoPromotionEnabled: true
      activeDeadlineSeconds: 600
      scaleDownDelaySeconds: 300
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.24
        ports:
        - containerPort: 80
